dataset:
  train_images: "data/train/images/"
  train_masks: "data/train/masks/"
  val_images: "data/val/images/"
  val_masks: "data/val/masks/"
  image_size: 1024
  batch_size: 4
  num_workers: 8

model:
  pretrained_model_name_or_path: "CompVis/stable-diffusion-v1-4-original"
  latent_dim: 512
  num_inference_steps: 50
  guidance_scale: 7.5

training:
  epochs: 50
  learning_rate: 1e-5
  weight_decay: 1e-4
  save_model_every: 5
  log_dir: "logs/"
  output_dir: "outputs/"